"""add_dialogues_table

Revision ID: 81fac960a2a7
Revises: ebf18b184d2e
Create Date: 2026-06-05 16:34:58.989259

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '81fac960a2a7'
down_revision: Union[str, None] = 'ebf18b184d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_type', sa.Enum('USER', 'CHARACTER', name='speakertype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogues')
    # ### end Alembic commands ###
