"""update_models

Revision ID: ebf18b184d2e
Revises: f74e0002f300
Create Date: 2026-06-05 13:32:52.325960

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ebf18b184d2e'
down_revision: Union[str, None] = 'f74e0002f300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.add_column('characters', sa.Column('prompt', sa.Text(), nullable=False))
    op.drop_column('characters', 'system_prompt')
    op.drop_column('characters', 'background')
    op.drop_column('characters', 'appearance')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('worlds', 'rules',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worlds', 'rules',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('characters', sa.Column('appearance', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('background', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('characters', 'prompt')
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###
